# These are supported funding model platforms

github: [itsRabb]
patreon:
open_collective:
ko_fi: devrabb
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: devrabb
thanks_dev:
custom:
